repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: destroyed-symlinks
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-bandit',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'flake8-print',
            'flake8-pytest-style',
            'flake8-simplify',
        ]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            'types-requests',
            'types-PyYAML',
        ]

-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.1.1
    hooks:
    -   id: sqlfluff-lint
        args: [--dialect, postgres]
    -   id: sqlfluff-fix
        args: [--dialect, postgres]

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
    -   id: terraform_tflint
    -   id: terraform_tfsec
    -   id: terraform_docs

-   repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
    -   id: hadolint
        args: ['--ignore', 'DL3008', '--ignore', 'DL3013', '--ignore', 'DL3018']

-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
    -   id: gitleaks

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
    -   id: python-safety-dependencies-check

-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
    -   id: docker-compose-check

-   repo: local
    hooks:
    -   id: check-postgres-security
        name: Check PostgreSQL Security
        entry: scripts/security/check_postgres_security.sh
        language: script
        files: '^(security_tiers|config)/.*\.(sql|conf)$'
        pass_filenames: true
