apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-security
data:
  POSTGRES_DB: postgres
  postgresql.conf: |
    # Memory Configuration
    shared_buffers = 1GB
    work_mem = 32MB
    maintenance_work_mem = 256MB
    effective_cache_size = 3GB

    # Connection Settings
    max_connections = 100
    listen_addresses = '*'
    
    # WAL Configuration
    wal_level = replica
    max_wal_size = 1GB
    min_wal_size = 80MB
    
    # Monitoring
    shared_preload_libraries = 'pg_stat_statements,auto_explain'
    pg_stat_statements.track = all
    pg_stat_statements.max = 10000
    
    # Logging
    log_destination = 'stderr'
    logging_collector = off
    log_min_duration_statement = 1000
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_lock_waits = on
    log_temp_files = 0
    log_autovacuum_min_duration = 0
    log_error_verbosity = default
    
    # Security
    password_encryption = scram-sha-256
    ssl = on
    ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'
    ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'

  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all            all                                     scram-sha-256
    host    all            all             127.0.0.1/32           scram-sha-256
    host    all            all             ::1/128                scram-sha-256
    hostssl all            all             0.0.0.0/0             scram-sha-256 