- name: Schedule Encrypted PostgreSQL Backups
  hosts: db_servers
  become: yes

  tasks:
    - name: Add pgBackRest encrypted backup job to cron
      cron:
        name: "pgBackRest Encrypted Backup"
        job: "/usr/bin/pgbackrest --stanza=db_dev --log-level-console=info backup && gpg --batch --encrypt --recipient ${{ secrets.GPG_RECIPIENT }} --output /var/lib/pgbackrest/pgbackrest-$(date +%F).tar.gz.gpg /var/lib/pgbackrest/pgbackrest-$(date +%F).tar.gz"
        minute: "0"
        hour: "2"
        user: postgres

    - name: Add AWS S3 upload job
      cron:
        name: "Upload Encrypted Backups to S3"
        job: "aws s3 sync /var/lib/pgbackrest/ s3://your-encrypted-backups-bucket/"
        minute: "30"
        hour: "2"
        user: postgres

