global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-examples:5432']
    metrics_path: /metrics
    scheme: http
