apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-security-network-policy
  namespace: postgres-security
spec:
  podSelector:
    matchLabels:
      app: postgres-security
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: app-server
    - podSelector:
        matchLabels:
          role: monitoring
    ports:
    - protocol: TCP
      port: 5432
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53  # DNS
    - protocol: UDP
      port: 53  # DNS 