apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: postgres-security
type: Opaque
data:
  # Values are base64 encoded
  # Example: echo -n "postgres" | base64
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: c2VjdXJlcGFzc3dvcmQ=  # securepassword
  POSTGRES_DB: ZGJfZGV2  # db_dev 