apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Tag               postgres.*
        Path              /var/log/postgresql/*.log
        Parser            postgresql
        DB                /var/log/flb_postgres.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [INPUT]
        Name              tail
        Tag               postgres.audit
        Path              /var/log/postgresql/audit/*.log
        Parser            postgresql
        DB                /var/log/flb_postgres_audit.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name                kubernetes
        Match               postgres.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name                grep
        Match               postgres.*
        Regex              log ERROR|FATAL|PANIC|WARNING

    [OUTPUT]
        Name               es
        Match              postgres.*
        Host               elasticsearch-master
        Port               9200
        HTTP_User          ${ES_USER}
        HTTP_Passwd        ${ES_PASSWORD}
        Logstash_Format    On
        Logstash_Prefix    postgres
        Time_Key           @timestamp
        Generate_ID        On
        Replace_Dots       On
        Retry_Limit        False
        tls                On
        tls.verify         Off

    [OUTPUT]
        Name               datadog
        Match              postgres.*
        Host               http-intake.logs.datadoghq.com
        TLS               On
        apikey            ${DD_API_KEY}
        dd_service        postgres
        dd_source         postgresql
        dd_tags           env:${DD_ENV}

  parsers.conf: |
    [PARSER]
        Name           postgresql
        Format         regex
        Regex         ^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} \w+) \[(?<pid>\d+)\] (?<level>\w+): \s*(?<message>.*)$
        Time_Key      time
        Time_Format   %Y-%m-%d %H:%M:%S %Z
        Time_Keep     On

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:2.1
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: username
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: password
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: api-key
        - name: DD_ENV
          valueFrom:
            configMapKeyRef:
              name: datadog-config
              key: environment
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers 