apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: '${SLACK_API_URL}'
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alertmanager@example.com'
      smtp_auth_username: '${SMTP_USERNAME}'
      smtp_auth_password: '${SMTP_PASSWORD}'

    templates:
      - '/etc/alertmanager/templates/*.tmpl'

    route:
      group_by: ['alertname', 'category']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'slack-notifications'
      routes:
      - match:
          severity: critical
        receiver: 'pagerduty-critical'
        continue: true
      - match:
          severity: warning
          category: resource
        receiver: 'email-devops'
      - match:
          severity: warning
          category: performance
        receiver: 'slack-performance'

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname']

    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#postgres-alerts'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        actions:
        - type: button
          text: 'View in Grafana'
          url: '{{ template "slack.grafana" . }}'

    - name: 'pagerduty-critical'
      pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        send_resolved: true
        description: '{{ template "pagerduty.description" . }}'
        client: 'Alertmanager'
        client_url: '{{ template "pagerduty.clientURL" . }}'

    - name: 'email-devops'
      email_configs:
      - to: 'devops@example.com'
        send_resolved: true
        headers:
          subject: '{{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'

    - name: 'slack-performance'
      slack_configs:
      - channel: '#postgres-performance'
        send_resolved: true
        title: '{{ template "slack.performance.title" . }}'
        text: '{{ template "slack.performance.text" . }}'

  templates/slack.tmpl: |
    {{ define "slack.title" }}
    [{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}
    {{ end }}

    {{ define "slack.text" }}
    *Alert:* {{ .GroupLabels.alertname }}
    *Description:* {{ .CommonAnnotations.description }}
    *Severity:* {{ .CommonLabels.severity }}
    *Category:* {{ .CommonLabels.category }}
    {{ if .CommonAnnotations.runbook_url }}*Runbook:* {{ .CommonAnnotations.runbook_url }}{{ end }}
    {{ if .CommonAnnotations.recommended_action }}*Recommended Action:* {{ .CommonAnnotations.recommended_action }}{{ end }}
    {{ end }}

    {{ define "slack.performance.title" }}
    [{{ .Status | toUpper }}] Performance Alert: {{ .GroupLabels.alertname }}
    {{ end }}

    {{ define "slack.performance.text" }}
    *Performance Alert:* {{ .GroupLabels.alertname }}
    *Description:* {{ .CommonAnnotations.description }}
    *Metrics:*
    {{ range .Alerts }}
    • {{ .Labels.instance }}: {{ .Annotations.value }}
    {{ end }}
    {{ end }} 