apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s
      external_labels:
        environment: production

    storage:
      tsdb:
        retention:
          time: 15d
          size: 50GB
        out_of_order_time_window: 30m

    rule_files:
      - /etc/prometheus/rules/*.yaml

    scrape_configs:
      - job_name: 'postgres'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - postgres-security
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: postgres
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "9187"
            action: keep
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'pg_.*'
            action: keep
        
      - job_name: 'node'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: node
            replacement: ${1}
        
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)

  rules/postgres_alerts.yaml: |
    groups:
    - name: PostgresAlerts
      rules:
      - alert: PostgresqlDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          category: availability
        annotations:
          summary: "PostgreSQL instance is down"
          description: "PostgreSQL instance has been down for more than 1 minute"
          runbook_url: "https://wiki.example.com/runbooks/postgresql/instance-down"

      - alert: PostgresqlHighConnections
        expr: sum(pg_stat_activity_count) > (pg_settings_max_connections * 0.8)
        for: 5m
        labels:
          severity: warning
          category: resource
        annotations:
          summary: "High number of PostgreSQL connections"
          description: "PostgreSQL instance is using more than 80% of available connections"
          recommended_action: "Consider connection pooling or increasing max_connections"

      - alert: PostgresqlSlowQueries
        expr: rate(pg_stat_activity_max_tx_duration{datname!~"template.*"}[1m]) > 300
        for: 2m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Slow PostgreSQL queries detected"
          description: "Queries taking more than 5 minutes to execute"
          recommended_action: "Check pg_stat_activity for blocking queries"

      - alert: PostgresqlReplicationLag
        expr: pg_stat_replication_lag_bytes > 100000000
        for: 5m
        labels:
          severity: warning
          category: replication
        annotations:
          summary: "PostgreSQL replication lag detected"
          description: "Replication is lagging by more than 100MB"

      - alert: PostgresqlHighCPU
        expr: rate(process_cpu_seconds_total{job="postgres"}[5m]) > 0.8
        for: 10m
        labels:
          severity: warning
          category: resource
        annotations:
          summary: "High CPU usage in PostgreSQL"
          description: "PostgreSQL is using more than 80% CPU for over 10 minutes"

      - alert: PostgresqlHighMemory
          description: "PostgreSQL replication is lagging by more than 100MB" 