- name: Schedule PostgreSQL Backups
  hosts: db_servers
  become: yes

  tasks:
    - name: Add pgBackRest backup job to cron
      cron:
        name: "pgBackRest Nightly Backup"
        job: "/usr/bin/pgbackrest --stanza=db_dev --log-level-console=info backup"
        minute: "0"
        hour: "2"
        user: postgres

    - name: Add Barman backup job to cron
      cron:
        name: "Barman Weekly Backup"
        job: "/usr/bin/barman backup db_dev"
        minute: "0"
        hour: "3"
        day: "1"
        user: postgres
