name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
        
    - name: Run linters
      run: |
        flake8 .
        pylint **/*.py

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up test environment
      run: |
        # Setup test environment
        echo "Setting up test environment"
        
    - name: Run unit tests
      run: |
        # Run unit tests
        echo "Running unit tests"
        
    - name: Run integration tests
      run: |
        chmod +x test/integration/integration_test.sh
        ./test/integration/integration_test.sh

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: cd terraform && terraform init
      
    - name: Terraform Plan
      run: cd terraform && terraform plan
      
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: cd terraform && terraform apply -auto-approve

  k8s-deploy:
    runs-on: ubuntu-latest
    needs: terraform-deploy
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to Kubernetes
      run: |
        # Deploy to Kubernetes cluster
        kubectl apply -f kubernetes/
