name: PostgreSQL Security Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Run at 2:00 AM every Monday
  workflow_dispatch:  # Allow manual triggering

jobs:
  security-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary sqlalchemy pandas requests pytest pytest-cov cryptography
    
    - name: Create pgcrypto extension
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
    
    - name: Run security tests
      run: |
        cd tests/security
        python postgres_security_tests.py
    
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: security-test-report
        path: |
          tests/security/security_test_report_*.html
          tests/security/security_test_report_*.json
          tests/security/security_tests.log
    
    - name: Publish test report
      if: success() || failure()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./tests/security
        destination_dir: security-reports
        keep_files: true
