name: PostgreSQL Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: db_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d db_dev"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Security Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlmap

      - name: Run SQL Injection Scans
        run: |
          sqlmap -u "http://localhost/api/v1/users?search=test" --dbms=PostgreSQL --batch --level=5 --risk=3 --random-agent --technique=BEUST

      - name: Check for Unauthorized Access
        run: psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -f test/pgTAP/04-security_test.sql

